### ISSUE TITLE
How to hide passwords while using shinytest2

### ISSUE THREAD

**Issue by shahronak47** [rstudio/shinytest2#211]
We have a shiny application that has a login screen where user can enter their username and password. I am trying to use `shinytest2` to record tests but it records the username and password in raw format in `test-shinytest2.R` file which is a serious security threat. 

I am not sure if this is common knowledge or something that I have missed to read but how do I ensure that I hide the password while recording the test?

**Comment by bersbersbers** [comment]
Nothing that `shinytest2` can do, but you could
1. store the password in an environment variable and pull it from there, so that the test script does not contain it,
2. maintain an allow-list on the Shiny app, i.e., a list of IPs/host names from where no password is needed, and test from that IP/host name, or
3. configure a maintenance user in the Shiny app whose credentials can be public.

I'd start with 1.

**Comment by schloerke** [comment]
Closing as solutions provided
