### ISSUE TITLE
`AppDriver$wait_for_js()` does not quote script input

### ISSUE THREAD

**Issue by fproske** [rstudio/shinytest2#236]
The `eval()` call in the `chromote_wait_for_condition ` function is essentially a NOP instruction as the `condition_js ` script is not quoted: https://github.com/rstudio/shinytest2/blob/61d51d9e96640bfae3eeefa12c4b685099b584c8/R/chromote-methods.R#L105
This leads to e.g. the input script `'test'==='test';` throwing a Javascript error:  `SyntaxError: Unexpected token ';'. Expected ')' to end an argument list.` as the code to be executed looks like this: `eval('test'==='test';)` which is obviously invalid syntax.
To fix this, the `condition_js` needs to be quoted properly.

**Comment by yogat3ch** [comment]
Hi @schloerke,
opening this back up because I found a bug where an object of class `glue, character` passed as the `condition_js` argument to `wait_for_js` will produce an error.

`app$wait_for_js(UU::glue_js("$('#*{ns('highlighted')}* table.dataTable > tbody > tr').length == 1;"))`

produces an error:
![image](https://user-images.githubusercontent.com/32208821/204570935-9f091b3c-1eab-44f8-86ac-68bebe08d173.png)

I think this can be resolved by simply wrapping `condition_js` on the line mentioned above in `as.character` as the following works:

`app$wait_for_js(as.character(UU::glue_js("$('#*{ns('highlighted')}* table.dataTable > tbody > tr').length == 1;")))`

**Comment by schloerke** [comment]
`{glue}` is so weird. lol.

Thank you for the fix!

**Comment by schloerke** [comment]
@yogat3ch Hopefully fixed in https://github.com/rstudio/shinytest2/pull/288

**Comment by yogat3ch** [comment]
@schloerke Very much appreciated!!! 🙏
